### PR TITLE
Documentation for hook stages

### PR DESCRIPTION
**Pull request by barrysteyn**
Documentation update for confining hooks to be run at a certain stage.

### CODE REVIEW

**Comment by asottile** [comment]
Want to add yourself to "Contributors" as well :D?

**Comment by barrysteyn** [comment]
Okay :)

**Comment by barrysteyn** [comment]
Done.

**Comment by asottile** [comment]
@barrysteyn hmmm why does it show @chriskuehl's commit as well?

**Comment by barrysteyn** [comment]
Yikes, my bad. I will fix this...

**Comment by barrysteyn** [comment]
Done!

**Comment by asottile** [comment]
Thanks again friend!

**Comment by barrysteyn** [comment]
An absolute pleasure...

**Pull request merged**
