### PR TITLE
add https://github.com/detailyang/pre-commit-shell

### PR DESCRIPTION
**Pull request by detailyang**
add pre commit hook for shell-check :beers:

### CODE REVIEW

**Comment by asottile** [comment]
Ah, you actually want to branch off of real_master and only change all-repos. The master branch is generated with Travis

**Comment by detailyang** [comment]
so just change file `all-repos.yaml` on real-master branch and travis.ci will generate github page, right? :grin:

**Comment by asottile** [comment]
Here's what I meant :D https://github.com/pre-commit/pre-commit.github.io/pull/78

**Comment by detailyang** [comment]
@asottile  gotcha

**Pull request closed without merging**
