### PR TITLE
Adding nbstripout to available hooks

### PR DESCRIPTION
**Pull request by ericmjl**
As per title.

Please let me know if I need to update anything else.

### CODE REVIEW

**Comment by asottile** [comment]
hooks should not invoke `git add`: https://github.com/kynan/nbstripout/blob/22f71272abcc719d84018e6abbd0a5f19eae6656/.pre-commit-hooks.yaml#L4

**Comment by ericmjl** [comment]
Thanks for the note, @asottile.

Pinging @kynan on this thread for context. I enjoy using nbstripout, and I'd also like to see nbstripout on the official list of supported pre-commit hooks. Is the `git add` step necessary? I think conforming to the standard "don't git add" might be preferable here though.

**Comment by kynan** [comment]
Yep, totally agree @ericmjl. We have a pending PR kynan/nbstripout#106 that will address this.

**Comment by kynan** [comment]
FWIW, this PR needs rebasing :)

**Comment by ericmjl** [comment]
Thanks @kynan! Updated! :smile:

**Comment by kynan** [comment]
FYI, kynan/nbstripout#106 is now merged.

**Comment by asottile** [comment]
sweet

**Pull request merged**
