### PR TITLE
Add dockerfilelint

### PR DESCRIPTION
**Pull request by pryorda**
Add dockerfilelint hook for others that is based on https://github.com/replicatedhq/dockerfilelint

### CODE REVIEW

**Comment by asottile** [comment]
Hmm! I'll look into the build failing -- did you propose adding the metadata upstream? I think that would be preferable :)

**Comment by pryorda** [comment]
They have not done any updates in awhile. I can submit a PR if you want.

**Comment by pryorda** [comment]
Should I close this out or could it be merged?

**Comment by asottile** [comment]
oops! lost track of this -- sorry can you rebase to fix the build error (and append to the bottom of the list? it's currently not really ordered but I plan to fix that at some point) -- Thanks and sorry for the delay!

**Comment by pryorda** [comment]
Alright, Alright, Alight. 

Looks to be rebased.

**Pull request merged**
